---
version: "3.8"
services:
  movies:
    image: nikhitha5819/movies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: nikhitha5819/train:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: nikhitha5819/recharge:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: nikhitha5819/dth:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
